openapi: 3.0.0
servers:
  - url: "https://api.learnir.co/v1"
info:
  title: Learnir Javascript SDK
  description: Welcome to the Learnir Javascript sdk, get your content right in the browser anywhere and everywhere.
  version: 1.1.1
  contact:
    name: Learnir Engineering
    url: https://learnir.co
paths:
  /integration/sdk/content:
    get:
      tags: ["learnir"]
      summary: Get your Port content
      description: "Gets an Array of your content boxes(objects) in a formatted manner"
      operationId: content
      parameters:
        - name: consumer
          in: query
          description: The id of the created consumer
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Content is ready
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Content"
        "404":
          description: Port access key is invalid or not present
  /integration/sdk/consumer:
    post:
      tags: ["learnir"]
      summary: Create a New Consumer on Learnir
      description: "This creates a consumer using the details you provide and in future helps us identify when someone particular is making use of your content boxes"
      operationId: consumer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Consumer"
      responses:
        "200":
          description: Consumer Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Consumer"
        "404":
          description: Create Consumer Error, support + data recheck.
  /integration/sdk/consumer/event:
    post:
      tags: ["learnir"]
      summary: Record learning experience event
      description: "This creates an consumer analytics event, used in showing you how your learning experience is used and performing"
      operationId: record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        "200":
          description: Consumer Event Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Consumer"
        "404":
          description: Create consumer event error, support + data recheck.
  /integration/sdk/consumer/events/{id}:
    get:
      tags: ["learnir"]
      summary: Get consumer events
      description: "Gets an Array of your consumer events(objects) for answers on learning states. etc"
      operationId: records
      parameters:
        - name: id
          in: path
          description: The id of the created consumer
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Consumer events is ready
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Events"
        "404":
          description: Data requirements un-met. (Consumer_id and distribution_port)
  /integration/sdk/consumer/interactions/{id}:
    get:
      tags: ["learnir"]
      summary: Get consumer interactions data
      description: "Gets an Array of your consumer interactions(objects) data. - e.g certification, quizzes data etc"
      operationId: interactions
      parameters:
        - name: id
          in: path
          description: The id of the created consumer
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Consumer interactions is ready
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Interactions"
        "404":
          description: Data requirements un-met. (Consumer_id and distribution_port)

components:
  schemas:
    Consumer:
      title: Content Consumer
      description: Creation of a User to allow access to locked resources
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        image:
          type: string
    Box:
      title: Content Box
      description: Base of content boxes, is dynamic though
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
    Content:
      type: array
      items:
        $ref: "#/components/schemas/Box"
    Event:
      title: Consumer analytics event
      description: Record usage of a consumer in your learning experience
      type: object
      properties:
        consumer:
          type: string
        event:
          type: string
        context:
          type: object
    Events:
      type: array
      items:
        $ref: "#/components/schemas/Event"
    Interaction:
      title: Consumer interaction object
      description: Interaction data saved when consumer worked with a component
      type: object
      properties:
        identifier:
          type: string
        comp:
          type: string
        component:
          type: string
        id:
          type: string
    Interactions:
      type: array
      items:
        $ref: "#/components/schemas/Interaction"
