name: Build learnir SDK CLients
on:
  push:
    branches:
      - main
jobs:
  run-client-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: true
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Build SDK clients, Publish for Deployment 🚀
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          npm install @openapitools/openapi-generator-cli -g
          openapi-generator-cli generate -g typescript-axios -i ./sdk-spec.yaml -o sdks/learnir-javascript-sdk -p npmName=learnir-javascript-sdk,supportsES6=true,modelPropertyNaming=original
          cd sdks/learnir-javascript-sdk
      - name: Push generated js sdk to it's repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "sdks/learnir-javascript-sdk"
          destination-github-username: "Learnir"
          destination-repository-name: "learnir-javascript-sdk"
          user-email: henry@learnir.co
          target-branch: main
      - name: Build learnir-javascript-sdk to NPM
        run: |
          cd sdks/learnir-javascript-sdk
          npm install && npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_LEARNIR_TOKEN }}